### ISSUE TITLE
record fields indentation

### ISSUE THREAD

**Issue by avsm** [ocaml-doc/doc-ock-html#7]
From @hannesm in https://github.com/mirage/mirage/issues/609#issuecomment-258390884

> odoc output: no line breaks in sum types (see  http://docs.mirage.io/odoc/tls/Config/index.html#/own_cert.typ), fields of record types are not indented (see http://docs.mirage.io/odoc/tls/Config/index.html#/config.typ)

**Comment by trefis** [comment]
The first one is not actually a sum type (and the difference does matter in this case), however a recent commit introduced non breaking space in a few places so that @dbuenzli could do the formatting from CSS (including line breaking on normal spaces).
So hopefully this will get better soon.

As for the second issue, I think the solution is probably a CSS one here again. But I'll see what Daniel comes up with.

**Comment by dbuenzli** [comment]
@trefis As I said [there](https://github.com/mirage/mirage/issues/609#issuecomment-258432221) I'm basically waiting that you make a first big round on the issues I reported before working on this again. I also don't think it's worth for people to report issues before this has happened.

**Comment by dbuenzli** [comment]
We'll make sure that this gets correctly rendered. In any case please open issues in the `odoc` repository.
